name: Docker Image CI
on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
jobs:

 build:
 
  runs-on: ubuntu-latest
  
  steps:
  -
   name: Checkout
    cd mysite
   uses: actions/checkout@v3
  -
   name: Login to Docker Hub
    cd mysite
   uses: docker/login-action@v2
   with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
  -
   name: Set up Docker Buildx
    cd mysite
   uses: docker/setup-buildx-action@v2
  -
   name: Build and push
    cd mysite
   uses: docker/build-push-action@v3
   with:
    context: .
    file: Dockerfile
    push: true
    tags: ${{ secrets.DOCKERHUB_USERNAME }}/django-docker:latest
